version: '3.4'

services: 
  catalogdb:
    image: mongo
    container_name: catalogdb
    ports:
      - 27017:27017
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    container_name: catalog.api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    depends_on: 
      - catalogdb
    ports:
      - 5291:80